team2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^umbrella_system/', include('umbrella_system.urls')),
    url(r'^admin/', admin.site.urls),
]

umbrella_system/urls.py
from django.conf.urls import url

from . import views

app_name = 'umbrella_system'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # ex: /umbrella_system/201606/date/
    url(r'^(?P<dates>[0-9]+)/date/$', views.date, name='date'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login_go/$', views.login_go, name='login_go'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^(?P<dates>[0-9]+)/(?P<room>[0-9]+)/(?P<time>[0-9]+)/yoyaku/$', views.yoyaku, name='yoyaku'),
    url(r'^(?P<dates>[0-9]+)/(?P<room>[0-9]+)/(?P<time>[0-9]+)/yoyaku_del/$', views.yoyaku_del, name='yoyaku_del'),
    url(r'^yoyaku_touroku/$', views.yoyaku_touroku, name='yoyaku_touroku'),
    url(r'^yoyaku_del_go/$', views.yoyaku_del_go, name='yoyaku_del_go'),
    url(r'^(?P<dates>[0-9]+)/zikanwari/$', views.zikanwari, name='zikanwari'),
]

umbrella_system/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=200)
    seats = models.IntegerField(default=0)
    def __unicode__(self):
        return self.name

class Genre(models.Model):
    name = models.CharField(max_length=200)
    def __unicode__(self):
        return self.name

class User(models.Model):
    user_ids = models.CharField(max_length=20)
    user_name = models.CharField(max_length=20,default='')
    password = models.CharField(max_length=8)
    def __unicode__(self):
        return self.user_name

class Order(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    time_zone_id = models.IntegerField(default=0)
    order_day = models.DateTimeField('date published')
    charge_lv = models.IntegerField(default=0)
    def __unicode__(self):
        return self.room.name

class Holiday(models.Model):
    name = models.CharField(max_length=20)
    holiday_date = models.DateTimeField('date published')
    def __unicode__(self):
        return self.name

umbrella_system/views.py
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.template import loader, RequestContext
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
import time,datetime
import calendar
from .models import Room,Genre,User,Order,Holiday


def get_weekday(week):
    if week==0 :
        return 'Monday'
    elif week==1:
        return 'Tuesday'
    elif week==2:
        return 'Wednesday'
    elif week==3:
        return 'Thursday'
    elif week==4:
        return 'Friday'
    elif week==5:
        return 'Saturday'
    else:
        return 'Sunday'
def get_time_seet(flg_holiday):
    if (flg_holiday):
        return ['10:00~11:00', '11:15~12:15', '13:15~14:15', '14:30~15:30', '15:45~16:45']
    else:
        return ['15:00~16:00', '16:15~17:15', '17:30~18:30']

def	index(request):
	return render(request,'umbrella_system/index.html')

def	date(request, dates):
    gdate = int(dates)
    year = gdate//10000
    day = gdate%100
    month = (gdate%10000-day)//100

    if 'login_user' in request.session:
        session = dict({'login_user':request.session['login_user']})
    else:
            return HttpResponseRedirect(reverse('umbrella_system:login'))

    calendar.setfirstweekday(calendar.SUNDAY)
    dt = datetime.datetime.fromtimestamp(time.mktime((year, month+1, 1, 0, 0, 0, 0, 0, 0)))
    next_date = dict({'year':dt.year,'month':dt.month,})
    dt = datetime.datetime.fromtimestamp(time.mktime((year, month-1, 1, 0, 0, 0, 0, 0, 0)))
    last_date = dict({'year':dt.year,'month':dt.month,})
    cal = dict({'year':year,'month':month,'day':day,'days':calendar.monthcalendar(year, month),})
    dt = datetime.datetime(year, month, day)
    rooms = Room.objects.all()

    day_of_week = datetime.date(year, month, day).weekday()
    try:
        selected_holiday = Holiday.objects.get(holiday_date=dt)
    except (KeyError, Holiday.DoesNotExist,):
        holiday = ''
    else:
        holiday = dict({'holiday_name': selected_holiday.name})
    if (day_of_week == 5 or day_of_week == 6 or 'holiday_name' in holiday):
        time_set = 6
        time_seet = get_time_seet(True)
    else:
        time_set = 4
        time_seet = get_time_seet(False)
    roomset=[]
    for rooma in rooms:
        orders = Order.objects.filter(room=rooma,order_day=dt)
        wari=[]

        for i in range(1, time_set):
            wari.append(dict({'time':i,'time_zone':time_seet[i-1],}))
        for order in orders:
            wari[order.time_zone_id-1] = dict({'time':order.time_zone_id,'time_zone':time_seet[order.time_zone_id-1],'user_id':order.user.user_ids,'user_name':order.user.user_name,'genre':order.genre.name})
        wari = sorted(wari, key=lambda wari: wari['time'])
        roomset.append(dict({'room_name':rooma.name,'seats':rooma.seats,'wari':wari}))

    contexts = dict({'cal':cal,'next_date':next_date,'last_date':last_date,'rooms':Room.objects.all(),'roomset':roomset})
    contexts.update(session)
    contexts.update(holiday)


    return HttpResponse(render(request,'umbrella_system/date.html',contexts))

def login(request):
    contexts = dict({'error_messages': ''})
    if 'login_user' in request.session:
        session = dict({'login_user':request.session['login_user']})
        dt = datetime.date.today()
        if(dt.month//10==0):
            date = str(dt.year)+'0'+str(dt.month)+'01'
        else:
            date = str(dt.year)+''+str(dt.month)+'01'
        return HttpResponseRedirect(reverse('umbrella_system:date', args=(date,)))
    return HttpResponse(render(request, 'umbrella_system/login.html', contexts))

def login_go(request):
    try:
        selected_user=User.objects.get(user_ids=request.POST['login_user'])
    except (KeyError,User.DoesNotExist,):
            contexts = dict({'error_messages': 'NO ID OR PASSWORD'})
            return HttpResponse(render(request, 'umbrella_system/login.html', contexts))
    else:
        if selected_user.password != request.POST['password']:
            contexts = dict({'error_messages': 'NO ID OR PASSWORD'})
            return HttpResponse(render(request, 'umbrella_system/login.html', contexts))
        else:
            request.session['login_user'] = selected_user.user_ids
            dt = datetime.date.today()
            if(dt.month//10==0):
                date = str(dt.year)+'0'+str(dt.month)+'01'
            else:
                date = str(dt.year)+''+str(dt.month)+'01'
            return HttpResponseRedirect(reverse('umbrella_system:date', args=(date,)))


def logout(request):
    if 'login_user' in request.session:
        del request.session['login_user']
    contexts = dict({'error_messages': ''})

    return HttpResponseRedirect(reverse('umbrella_system:login',))

def yoyaku(request,dates,room,time):
    if 'login_user' in request.session:
        session = dict({'login_user':request.session['login_user']})
    else:
        return HttpResponseRedirect(reverse('umbrella_system:login'))
    year = int(dates)//10000
    day = int(dates)%100
    month = (int(dates)%10000-day)//100
    dt = datetime.datetime(year, month, day)
    try:
        if (Order.objects.filter(room=Room.objects.get(name=room), time_zone_id=time, order_day=dt).count() > 0):
            raise Http404
        else:
            selected_genre = Genre.objects.all()
            contexts = dict({'genres': selected_genre, 'date': dates, 'time': time, 'room': room})
            return HttpResponse(render(request, 'umbrella_system/yoyaku.html', contexts))
    except (KeyError, Room.DoesNotExist):
        raise Http404

def yoyaku_touroku(request):
    if 'login_user' in request.session:
        session = dict({'login_user':request.session['login_user']})
        uname = request.session['login_user']
    else:
            return HttpResponseRedirect(reverse('umbrella_system:login'))
    try:

        selected_genre = Genre.objects.get(name=request.POST['genres'])
        selected_user = User.objects.get(user_ids=uname)
        selected_room = Room.objects.get(name=request.POST['room'])
        order = Order()
    except (KeyError, Room.DoesNotExist,User.DoesNotExist,Genre.DoesNotExist):
        contexts = dict({'error_message': 'NO DATE'})
        return HttpResponse(render(request, 'umbrella_system/index.html', contexts))
    else:
        year = int(request.POST['date'])//10000
        day = int(request.POST['date'])%100
        month = (int(request.POST['date'])%10000-day)//100
        dt = datetime.datetime(year, month, day)
        order.room = selected_room
        order.genre = selected_genre
        order.user = selected_user
        order.time_zone_id = request.POST['time']
        order.order_day = dt
        order.charge_lv = request.POST['charge_lv']
        order.save()
        return HttpResponseRedirect(reverse('umbrella_system:date', args=(request.POST['date'],)))
def yoyaku_del(request,dates,room,time):
    if 'login_user' in request.session:
        session = dict({'login_user':request.session['login_user']})
    else:
        return HttpResponseRedirect(reverse('umbrella_system:login'))
    year = int(dates)//10000
    day = int(dates)%100
    month = (int(dates)%10000-day)//100
    dt = datetime.datetime(year, month, day)
    try:
        if (Order.objects.filter(room=Room.objects.get(name=room), time_zone_id=time, order_day=dt,user=User.objects.get(user_ids=request.session['login_user'])).count() == 1):
            selected_order = Order.objects.get(room=Room.objects.get(name=room), time_zone_id=time, order_day=dt,user=User.objects.get(user_ids=request.session['login_user']))
            contexts = dict({'room': selected_order.room.name, 'date': dates, 'time': selected_order.time_zone_id, 'genre': selected_order.genre,'charge':selected_order.charge_lv})
            return HttpResponse(render(request, 'umbrella_system/yoyakudel.html', contexts))
        else:
            raise Http404
    except (KeyError, Room.DoesNotExist,User.DoesNotExist):
        raise Http404
def yoyaku_del_go(request):
    if 'login_user' in request.session:
        session = dict({'login_user':request.session['login_user']})
        uname = request.session['login_user']
    else:
            return HttpResponseRedirect(reverse('umbrella_system:login'))
    try:
        selected_user = User.objects.get(user_ids=uname)
        selected_room = Room.objects.get(name=request.POST['room'])
    except (KeyError, Room.DoesNotExist,User.DoesNotExist,Genre.DoesNotExist):
        raise Http404
    else:
        year = int(request.POST['date'])//10000
        day = int(request.POST['date'])%100
        month = (int(request.POST['date'])%10000-day)//100
        dt = datetime.datetime(year, month, day)
        selected_order = Order.objects.get(room=selected_room,user=selected_user,time_zone_id=request.POST['time'], order_day=dt).delete()
        return HttpResponseRedirect(reverse('umbrella_system:date', args=(request.POST['date'],)))

def	zikanwari(request, dates):
    gdate = int(dates)
    year = gdate//100
    month = gdate%100

    if 'login_user' in request.session:
        session = dict({'login_user':request.session['login_user']})
    else:
            return HttpResponseRedirect(reverse('umbrella_system:login'))

    dt = datetime.datetime.fromtimestamp(time.mktime((year, month+1, -1, 0, 0, 0, 0, 0, 0)))
    cal = dict({'year':year,'month':month,})


    dt = datetime.datetime(year, month, 1)
    rooms = Room.objects.all()
    calendar.setfirstweekday(calendar.SUNDAY)
    days = calendar.monthcalendar(year, month)
    for i in range(0, len(days)):
        weeks = []
        for day in days[i]:
            if day > 0:
                day_of_week = datetime.datetime(year, month, day).weekday()
                try:
                    selected_holiday = Holiday.objects.get(holiday_date=datetime.datetime(year, month, day))
                except (KeyError, Holiday.DoesNotExist,):
                    holiday = ''
                else:

umbrella_system/templates/umbrella_system/date.html
<html>
    <head>
        <title>date</title>
        <style>
            td{
                text-align:center;
            }
            header{
                clear:both;
            }
            #calender{
                float:left;
            }
            #rooms{
                float:left;
            }
            .cal_day a:visited{
                color:blue;
            }
            .cal_day:nth-child(1) a:link{
                color:red;
            }
            .cal_day:nth-child(7n) a:link{
                color:red;
            }
            .cal_day:nth-child(7n+1) a:link{
                color:red;
            }
            .cal_day:nth-child(1) a:visited{
                color:red;
            }
            .cal_day:nth-child(7n) a:visited{
                color:red;
            }
            .cal_day:nth-child(7n+1) a:visited{
                color:red;
            }
        </style>
    </head>
    <body>
        <header>
            <a href="{% url 'umbrella_system:logout' %}">ログアウト</a>
        </header>
        <main>
            <a href="../../{{cal.year}}{%if cal.month < 10%}0{%endif%}{{cal.month}}/zikanwari">{{cal.month}}月の時間割</a>
            <br>
            <div id="calender">
                <fieldset>
                    <legend>カレンダー</legend>
                    <center>
                        <a href="../../{{last_date.year}}{%if last_date.month < 10%}0{%endif%}{{last_date.month}}01/date"><<{{last_date.year}}年{{last_date.month}}月</a>
                        <a href="../../{{next_date.year}}{%if next_date.month < 10%}0{%endif%}{{next_date.month}}01/date">{{next_date.year}}年{{next_date.month}}月>></a>
                        <table>
                            <tr>
                                <td colspan="7">{{cal.year}}年{{cal.month}}月</td>
                            </tr>
                            <tr>
                                <td>日</td>
                                <td>月</td>
                                <td>火</td>
                                <td>水</td>
                                <td>木</td>
                                <td>金</td>
                                <td>土</td>
                            </tr>
                        {% for days in cal.days %}
                            <tr>{% for day in days %}
                                <td class="cal_day">{%if day != 0%}<a href="../../{{cal.year}}{%if cal.month < 10%}0{%endif%}{{cal.month}}{%if day < 10%}0{%endif%}{{day}}/date">{%if day < 10%}0{%endif%}{{day}}</a>{%else%}{%endif%}</td>{% endfor %}
                            </tr>
                            {% endfor %}
                        </table>
                    </center>
                </fieldset>
            </div>
            <div id="rooms">
                {{cal.day}}日{%if holiday_name%}:{{holiday_name}}{%endif%}
                <fieldset>
                    <legend>教室一覧</legend>
                    {% for room in roomset %}
                        <table border="1">
                            <tr>
                                <td colspan="10">{{room.room_name}}教室:{{room.seats}}人</td>
                            </tr>
                            <tr>
                                <td>時間</td>
                                {% for wari in room.wari %}
                                    <td>{{wari.time_zone}}</td>
                                {% endfor %}
                            </tr>
                            <tr>
                                <td>予約状況</td>
                                {% for wari in room.wari %}
                                    {% if wari.user_id %}
                                        <td>{{wari.user_name}}</br>{{wari.genre}}</br>{% ifequal wari.user_id login_user %}<button onClick="location.href='../../{{cal.year}}{%if cal.month < 10%}0{%endif%}{{cal.month}}{%if cal.day < 10%}0{%endif%}{{cal.day}}/{{room.room_name}}/{{wari.time}}/yoyaku_del'">取消</button>{% endifequal %}</td>
                                    {% else %}
                                        <td><button onClick="location.href='../../{{cal.year}}{%if cal.month < 10%}0{%endif%}{{cal.month}}{%if cal.day < 10%}0{%endif%}{{cal.day}}/{{room.room_name}}/{{wari.time}}/yoyaku'">予約</button></td>
                                    {% endif %}
                                {% endfor %}
                            </tr>
                        </table>
                        </br>
                    {% endfor %}
                </fieldset>
            </div>
        </main>
        <footer></footer>
    </body>
</html>

umbrella_system/templates/umbrella_system/index.html
<html>
    <head>
        <title>index</title>
    </head>
    <body>
        <h2>index</h2>
    </body>
</html>

umbrella_system/templates/umbrella_system/login.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/login.css' %}" />

<div align="center">
	<form action="{% url 'umbrella_system:login_go'%}" method="post">
		{{error_messages}}
		{% csrf_token %}
		<table border="0">
			<tr>
				<th>
					ユーザID
				</th>
					<td>
						<input type="text" name="login_user" value="" size="24">
					</td>
			</tr>

			<tr>
				<th>
					パスワード
				</th>
					<td>
						<input type="text" name="password" value="" size="24">
					</td>
			</tr>

			<tr>
				<td>
					<input type="submit" value="ログイン" size="24"/>
				</td>
			</tr>
		</table>
	</form>
</div>

umbrella_system/templates/umbrella_system/yoyaku.html
<html>
    <head>
        <title>index</title>
    </head>
    <body>
        <h2>index</h2>
	    <form action="{% url 'umbrella_system:yoyaku_touroku'%}" method="post">
		{% csrf_token %}
            <input type="hidden" name="date" value="{{date}}" />
            <input type="hidden" name="time" value="{{time}}" />
            <input type="hidden" name="room" value="{{room}}" />
            <p>学年</p>
                <select name="charge_lv">
                    <option value="1">高学年</option>
                    <option value="2">中学年</option>
                    <option value="0">低学年</option>
                </select>
            <p>科目</p>
                <select name="genres">{% for genre in genres %}
                    <option value="{{genre}}">{{genre}}</option>
                    {% endfor %}
                </select>
            </br>
            <input type="submit" value="登録" />
        </form>
    </body>
</html>

umbrella_system/templates/umbrella_system/yoyakudel.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/yoyakudel.css' %}" />
<p>{{room}}</p>
<p>{{date}}</p>
<p>{{time}}</p>
<p>{{genre}}</p>
<p>{{charge}}</p>


<div id="p1">
	<p>予約を取り消しますか?</p>
	<form action="{% url 'umbrella_system:yoyaku_del_go'%}" method="post">
		{% csrf_token %}
			<input type="hidden" name="date" value="{{date}}" />
            <input type="hidden" name="time" value="{{time}}" />
            <input type="hidden" name="room" value="{{room}}" />
		<input type="submit" value="はい">
	</form>
	<button onclick="location.href='../../../../{{date}}/date'">いいえ</button>
</div>

umbrella_system/templates/umbrella_system/zikanwari.html
<html>
    <head>
        <title>date</title>
		<style>
            div table{
                float:left;
            }
            div{
                float:right;
            }
            .dan{
                float:left;
            }
            body{overflow:visible;
            }
            .holiday{
            	color:red;
            }
            #zikanwari{
                margin-right: auto;
                margin-left: auto;
            }
            #zikanwari *{
                white-space: nowrap;
            }
		</style>
    </head>
        <header>
            <a href="{% url 'umbrella_system:logout' %}">ログアウト</a>
        </header>
			{% load staticfiles %}
			{{cal.year}}
			{{cal.month}}
			</br>
			<table id="zikanwari">
				{%for day_set in days%}
					<tr>
					{%for day in day_set%}
						<td>
							{% ifnotequal day 0 %}
								<table {% ifequal day.weekday 'Sunday' %}class="holiday"{%endifequal%}{% ifequal day.weekday 'Saturday' %}class="holiday"{%endifequal%} border =1>
									<tr><td></td><td colspan={{day.time_seet|length}}>{{day.day}}日</td></tr>
									<tr><td></td><td colspan={{day.time_seet|length}}>{{day.weekday}}</td></tr>
									<tr><td></td>
										{% for time in day.time_seet %}
										<td>{{time}}</td>
										{%endfor%}
									</tr>
				{% for room in day.rooms %}
									<tr>
									<td>{{room.room_name}}</td>
										{% for wari in room.wari %}
											{% if wari.user %}
												<td>{{wari.user}}</br>{{wari.genre}}</br></td>
											{% else %}
												<td></td>
											{% endif %}
										{%endfor%}
									</tr>
									{%endfor%}
								</table>
							{%endifnotequal%}
						</td>
					{%endfor%}
					</tr>
				{%endfor%}
			</table>
        </main>
        <footer></footer>
    </body>
</html>